version: 2.1


commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  piline_id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id


workflows:
  piline_workflow:
    jobs:
      - piline_id
